let typeDescritptionSommaire = [
    "CLASSEMENT REGLEMENTAIRE DU PERMIS DE CONSTRUIRE",
    "AFFECTATION DES LOCAUX",
    "DESCRIPTION ARCHITECTURALE",
    "DESCRIPTION DES PRINCIPES CONSTRUCTIFS",
    "CONTRAINTES PARTICULIERE",
    "TECHNOLOGIE INNOVANTE",
    "CLASSEMENT DE L'ETABLISSEMENT EN FONCTION DES RISQUES",
    "LOCAUX A RISQUE PARTICULIER"
]

export default {'typeDS' : typeDescritptionSommaire};